### ISSUE TITLE
Allow for Static tokens as auth mechanism

### ISSUE THREAD

**Issue by dnitsch** [dnitsch/reststrategy#14]
Would be useful to allow for a static token passing as an auth mechanism.

something like `StaticTokenAuth` where the `AuthConfig` struct  `Username` field would be used as a header key and the `Password` would be used as the value

```yaml
auth:
  staticToken:
     username: X-API
     password: 128d9j0fwfr-0j43sefsdfg
```
