### ISSUE TITLE
Validate all vars 

### ISSUE THREAD

**Issue by dnitsch** [dnitsch/reststrategy#18]
Validate all vars inside the auth and seed actions - set in either `variables` or `runtimeVariables`. 

So that 

``` 
- name: create-pocketbase-user-for-qa-tes1
    endpoint: http://127.0.0.1:59886/api/users
    strategy: FIND/PATCH/POST
    getEndpointSuffix: "?page=1&perPage=100&sort=-created&filter="
    findByJsonPathExpr: "$.items[?(@.email=='qa-guy@example.com')].id"
    authMapRef: customTest1
    payloadTemplate: |
      {"email":"qa-guy@example.com","password":"Password123_alwaysChange","passwordConfirm":"Password123_alwaysChange"}
    patchPayloadTemplate: |
      {"password":"${newPass}","passwordConfirm":"${newPass}","unknown":"${unknown_var}"}
    variables:
      newPass: AWSPARAMSTR:///int-test/pocketbase/admin-pwd
```

an error is raised at to signify that `unknown_var` has no source.
